{
  config,
  lib,
  namespace,
  ...
}:
with lib;
with lib.${namespace};
let
  cfg = config.programs.terminal.zellij;
in
{
  options.programs.terminal.zellij = with types; {
    enable = mkBoolOpt false "enable zellij";
  };

  config = mkIf cfg.enable {

    home.programs.zellij = {
      enable = true;
      enableFishIntegration = true;
    };
    home.file.".config/zellij/config.kdl".text = ''
      //
      // THIS FILE WAS AUTOGENERATED BY ZELLIJ, THE PREVIOUS FILE AT THIS LOCATION WAS COPIED TO: /home/ghost/.config/zellij/config.kdl.bak
      //

      keybinds clear-defaults=true {
          normal {
              bind "?" {
                  LaunchOrFocusPlugin "zj-forgot" {
                      floating true
                  }
                  SwitchToMode "locked"
              }
              bind "J" { GoToNextTab; }
              bind "K" { GoToPreviousTab; }
              bind "Shift S" { NewPane "down"; SwitchToMode "locked"; }
              bind "Shift V" { NewPane "right"; SwitchToMode "locked"; }
              bind "v" { SwitchToMode "pane"; }
          }
          locked {
              bind "Ctrl g" { SwitchToMode "normal"; }
          }
          pane {
              bind "left" { MoveFocus "left"; }
              bind "down" { MoveFocus "down"; }
              bind "up" { MoveFocus "up"; }
              bind "right" { MoveFocus "right"; }
              bind "c" { SwitchToMode "renamepane"; PaneNameInput 0; }
              bind "d" { NewPane "down"; SwitchToMode "locked"; }
              bind "e" { TogglePaneEmbedOrFloating; SwitchToMode "locked"; }
              bind "f" { ToggleFocusFullscreen; SwitchToMode "locked"; }
              bind "i" { TogglePanePinned; SwitchToMode "locked"; }
              bind "j" { MoveFocus "down"; }
              bind "k" { MoveFocus "up"; }
              bind "n" { NewPane; SwitchToMode "locked"; }
              bind "p" { SwitchToMode "normal"; }
              bind "r" { NewPane "right"; SwitchToMode "locked"; }
              bind "v" { NewPane "right"; SwitchToMode "locked"; }
              bind "w" { ToggleFloatingPanes; SwitchToMode "locked"; }
              bind "x" { CloseFocus; SwitchToMode "locked"; }
              bind "z" { TogglePaneFrames; SwitchToMode "locked"; }
              bind "tab" { SwitchFocus; }
          }
          tab {
              bind "left" { GoToPreviousTab; }
              bind "down" { GoToNextTab; }
              bind "up" { GoToPreviousTab; }
              bind "right" { GoToNextTab; }
              bind "1" { GoToTab 1; SwitchToMode "locked"; }
              bind "2" { GoToTab 2; SwitchToMode "locked"; }
              bind "3" { GoToTab 3; SwitchToMode "locked"; }
              bind "4" { GoToTab 4; SwitchToMode "locked"; }
              bind "5" { GoToTab 5; SwitchToMode "locked"; }
              bind "6" { GoToTab 6; SwitchToMode "locked"; }
              bind "7" { GoToTab 7; SwitchToMode "locked"; }
              bind "8" { GoToTab 8; SwitchToMode "locked"; }
              bind "9" { GoToTab 9; SwitchToMode "locked"; }
              bind "[" { BreakPaneLeft; SwitchToMode "locked"; }
              bind "]" { BreakPaneRight; SwitchToMode "locked"; }
              bind "b" { BreakPane; SwitchToMode "locked"; }
              bind "h" { GoToPreviousTab; }
              bind "j" { GoToNextTab; }
              bind "k" { GoToPreviousTab; }
              bind "l" { GoToNextTab; }
              bind "n" { NewTab; SwitchToMode "locked"; }
              bind "r" { SwitchToMode "renametab"; TabNameInput 0; }
              bind "s" { ToggleActiveSyncTab; SwitchToMode "locked"; }
              bind "t" { SwitchToMode "normal"; }
              bind "x" { CloseTab; SwitchToMode "locked"; }
              bind "tab" { ToggleTab; }
          }
          resize {
              bind "left" { Resize "Increase left"; }
              bind "down" { Resize "Increase down"; }
              bind "up" { Resize "Increase up"; }
              bind "right" { Resize "Increase right"; }
              bind "+" { Resize "Increase"; }
              bind "-" { Resize "Decrease"; }
              bind "=" { Resize "Increase"; }
              bind "H" { Resize "Decrease left"; }
              bind "J" { Resize "Decrease down"; }
              bind "K" { Resize "Decrease up"; }
              bind "L" { Resize "Decrease right"; }
              bind "h" { Resize "Increase left"; }
              bind "j" { Resize "Increase down"; }
              bind "k" { Resize "Increase up"; }
              bind "l" { Resize "Increase right"; }
              bind "r" { SwitchToMode "normal"; }
          }
          move {
              bind "left" { MovePane "left"; }
              bind "down" { MovePane "down"; }
              bind "up" { MovePane "up"; }
              bind "right" { MovePane "right"; }
              bind "h" { MovePane "left"; }
              bind "j" { MovePane "down"; }
              bind "k" { MovePane "up"; }
              bind "l" { MovePane "right"; }
              bind "m" { SwitchToMode "normal"; }
              bind "n" { MovePane; }
              bind "p" { MovePaneBackwards; }
              bind "tab" { MovePane; }
          }
          scroll {
              bind "Alt left" { MoveFocusOrTab "left"; SwitchToMode "locked"; }
              bind "Alt down" { MoveFocus "down"; SwitchToMode "locked"; }
              bind "Alt up" { MoveFocus "up"; SwitchToMode "locked"; }
              bind "Alt right" { MoveFocusOrTab "right"; SwitchToMode "locked"; }
              bind "/" { SwitchToMode "entersearch"; SearchInput 0; }
              bind "e" { EditScrollback; SwitchToMode "locked"; }
              bind "f" { SwitchToMode "entersearch"; SearchInput 0; }
              bind "Alt h" { MoveFocusOrTab "left"; SwitchToMode "locked"; }
              bind "Alt j" { MoveFocus "down"; SwitchToMode "locked"; }
              bind "Alt k" { MoveFocus "up"; SwitchToMode "locked"; }
              bind "Alt l" { MoveFocusOrTab "right"; SwitchToMode "locked"; }
              bind "s" { NewPane "down"; SwitchToMode "locked"; }
          }
          search {
              bind "N" { Search "up"; }
              bind "c" { SearchToggleOption "CaseSensitivity"; }
              bind "n" { Search "down"; }
              bind "o" { SearchToggleOption "WholeWord"; }
              bind "w" { SearchToggleOption "Wrap"; }
          }
          session {
              bind "a" {
                  LaunchOrFocusPlugin "zellij:about" {
                      floating true
                      move_to_focused_tab true
                  }
                  SwitchToMode "locked"
              }
              bind "c" {
                  LaunchOrFocusPlugin "configuration" {
                      floating true
                      move_to_focused_tab true
                  }
                  SwitchToMode "locked"
              }
              bind "d" { Detach; }
              bind "o" { SwitchToMode "normal"; }
              bind "p" {
                  LaunchOrFocusPlugin "plugin-manager" {
                      floating true
                      move_to_focused_tab true
                  }
                  SwitchToMode "locked"
              }
              bind "q" {
                  LaunchOrFocusPlugin "zj-quit" {
                      floating true
                  }
                  SwitchToMode "locked"
              }
              bind "w" {
                  LaunchOrFocusPlugin "session-manager" {
                      floating true
                      move_to_focused_tab true
                  }
                  SwitchToMode "locked"
              }
          }
          shared_among "normal" "locked" {
              bind "Alt left" { MoveFocusOrTab "left"; }
              bind "Alt down" { MoveFocus "down"; }
              bind "Alt up" { MoveFocus "up"; }
              bind "Alt right" { MoveFocusOrTab "right"; }
              bind "Alt +" { Resize "Increase"; }
              bind "Alt -" { Resize "Decrease"; }
              bind "Alt =" { Resize "Increase"; }
              bind "Alt Shift H" { MoveFocus "left"; }
              bind "Alt Shift L" { MoveFocus "right"; }
              bind "Alt [" { PreviousSwapLayout; }
              bind "Alt ]" { NextSwapLayout; }
              bind "Alt f" { ToggleFloatingPanes; }
              bind "Alt h" { MoveFocusOrTab "left"; }
              bind "Alt i" { MoveTab "left"; }
              bind "Alt j" { MoveFocus "down"; }
              bind "Alt k" { MoveFocus "up"; }
              bind "Alt l" { MoveFocusOrTab "right"; }
              bind "Alt n" { NewPane; }
              bind "Alt o" { MoveTab "right"; }
              bind "¨" { GoToNextTab; }
              bind "©" { GoToPreviousTab; }
              bind "²" {
                  NewTab {
                      name ""
                  }
                  SwitchToMode "locked"
              }
              bind "Ctrl 1" { GoToTab 1; }
              bind "Ctrl 2" { GoToTab 2; }
              bind "Ctrl 3" { GoToTab 3; }
              bind "Ctrl 4" { GoToTab 4; }
          }
          shared_except "locked" "entersearch" {
              bind "enter" { SwitchToMode "locked"; }
          }
          shared_except "locked" "entersearch" "renametab" "renamepane" "prompt" "tmux" {
              bind "Ctrl g" { SwitchToMode "locked"; }
          }
          shared_except "locked" "entersearch" "renametab" "renamepane" {
              bind "esc" { SwitchToMode "locked"; }
          }
          shared_except "locked" "entersearch" "renametab" "renamepane" "move" {
              bind "m" { SwitchToMode "move"; }
          }
          shared_except "locked" "entersearch" "search" "renametab" "renamepane" "session" {
              bind "o" { SwitchToMode "session"; }
          }
          shared_except "locked" "tab" "entersearch" "renametab" "renamepane" {
              bind "t" { SwitchToMode "tab"; }
          }
          shared_except "locked" "tab" "scroll" "entersearch" "renametab" "renamepane" {
              bind "s" { SwitchToMode "scroll"; }
          }
          shared_among "normal" "resize" "tab" "scroll" "prompt" "tmux" {
              bind "p" { SwitchToMode "pane"; }
          }
          shared_among "normal" "pane" {
              bind "h" { MoveFocus "left"; }
              bind "l" { MoveFocus "right"; }
          }
          shared_except "locked" "resize" "pane" "tab" "entersearch" "renametab" "renamepane" {
              bind "r" { SwitchToMode "resize"; }
          }
          shared_among "scroll" "search" {
              bind "PageDown" { PageScrollDown; }
              bind "PageUp" { PageScrollUp; }
              bind "left" { PageScrollUp; }
              bind "down" { ScrollDown; }
              bind "up" { ScrollUp; }
              bind "right" { PageScrollDown; }
              bind "Ctrl b" { PageScrollUp; }
              bind "Ctrl c" { ScrollToBottom; SwitchToMode "locked"; }
              bind "d" { HalfPageScrollDown; }
              bind "Ctrl f" { PageScrollDown; }
              bind "h" { PageScrollUp; }
              bind "j" { ScrollDown; }
              bind "k" { ScrollUp; }
              bind "l" { PageScrollDown; }
              bind "u" { HalfPageScrollUp; }
          }
          entersearch {
              bind "Ctrl c" { SwitchToMode "scroll"; }
              bind "esc" { SwitchToMode "scroll"; }
              bind "enter" { SwitchToMode "search"; }
          }
          shared_among "entersearch" "prompt" "tmux" {
              bind "Ctrl space" { SwitchToMode "locked"; }
          }
          renametab {
              bind "esc" { UndoRenameTab; SwitchToMode "tab"; }
          }
          shared_among "renametab" "renamepane" {
              bind "Ctrl c" { SwitchToMode "locked"; }
          }
          renamepane {
              bind "esc" { UndoRenamePane; SwitchToMode "pane"; }
          }
      }

      // Plugin aliases - can be used to change the implementation of Zellij
      // changing these requires a restart to take effect
      plugins {
          about location="zellij:about"
          compact-bar location="zellij:compact-bar"
          configuration location="zellij:configuration"
          filepicker location="zellij:strider" {
              cwd "/"
          }
          plugin-manager location="zellij:plugin-manager"
          session-manager location="zellij:session-manager"
          status-bar location="zellij:status-bar"
          strider location="zellij:strider"
          tab-bar location="zellij:tab-bar"
          welcome-screen location="zellij:session-manager" {
              welcome_screen true
          }
          zj-forgot location="https://github.com/karimould/zellij-forgot/releases/latest/download/zellij_forgot.wasm"
          zj-quit location="https://github.com/cristiand391/zj-quit/releases/latest/download/zj-quit.wasm" {
              cancel_key "Esc"
              confirm_key "y"
          }
          zjstatus location="https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm"
          zjstatus-hints location="https://github.com/b0o/zjstatus-hints/releases/latest/download/zjstatus-hints.wasm" {
              max_length "0"
              overflow_str ""
              pipe_name "zjstatus_hints"
          }
      }

      load_plugins {
          zjstatus-hints
      }
      ui {
          pane_frames {
              rounded_corners true
          }
      }

      default_cwd "~"
       
      scroll_buffer_size 20000
       
      session_name "default"

      attach_to_session true
       
      show_startup_tips false
      
      scrollback_editor "/run/current-system/sw/bin/nvim"
    '';

    home.file.".config/zellij/layouts/default.kdl".text = ''
        layout {
          default_tab_template {
              children
              pane size=1 borderless=true {
                  plugin location="zjstatus" {
                      format_left   "{mode} {tabs}"
                      format_center ""
                      format_right  "{pipe_zjstatus_hints}{datetime}#[bg=#cba6f7,fg=#1e1e2e,bold] {session} "
                      format_space  ""

                      pipe_zjstatus_hints_format "#[fg=#1e1e2e,bold] {output} "

                      border_enabled  "false"
                      border_char     "─"
                      border_format   "#[fg=#6c7086]{char}"
                      border_position "top"

                      hide_frame_for_single_pane "true"

                      mode_locked      "#[bg=#cba6f7,fg=#1e1e2e,bold]  LOCK "
                      mode_normal      "#[bg=#f5c2e7,fg=#1e1e2e,bold]  NORMAL "
                      mode_resize      "#[bg=#f38ba8,fg=#1e1e2e,bold]  RESIZE "
                      mode_pane        "#[bg=#89b4fa,fg=#1e1e2e,bold]  PANE"
                      mode_move        "#[bg=#94e2d5,fg=#1e1e2e,bold]  MOVE "
                      mode_tab         "#[bg=#b4befe,fg=#1e1e2e,bold]  TAB "
                      mode_scroll      "#[bg=#cdd6f4,fg=#1e1e2e,bold]  SCROLL "
                      mode_search      "#[bg=#f9e2af,fg=#1e1e2e,bold]  SEARCH "
                      mode_entersearch "#[bg=#f9e2af,fg=#1e1e2e,bold]  ENTER SEARCH "
                      mode_renametab   "#[bg=#cba6f7,fg=#1e1e2e,bold]  RENAME TAB "
                      mode_renamepane  "#[bg=#cba6f7,fg=#1e1e2e,bold]  RENAME PANE "
                      mode_session     "#[bg=#f38ba8,fg=#1e1e2e,bold]  SESSION "
                      mode_tmux        "#[bg=#cdd6f4,fg=#1e1e2e,bold]  TMUX "

                      tab_active              "#[bg=#cba6f7,fg=#1e1e2e,bold] {index} {name} "
                      tab_active_fullscreen   "#[bg=#cba6f7,fg=#1e1e2e,bold] {fullscreen_indicator} {index} {name} "
                      tab_active_sync         "#[bg=#cba6f7,fg=#1e1e2e,bold] {sync_indicator} {index} {name} "

                      tab_normal              "#[fg=#6c7086,bold] {index} {name} "
                      tab_normal_fullscreen   "#[fg=#6c7086,bold] {fullscreen_indicator} {index} {name} "
                      tab_normal_sync         "#[fg=#6c7086,bold] {sync_indicator} {index} {name} "

                      tab_separator " "

                      tab_sync_indicator       "󰓦"
                      tab_fullscreen_indicator "󰊓"
                      tab_floating_indicator   "⬚"

                      tab_rename              "#[bg=#b4befe,fg=#1e1e2e,bold] {index} {name} {floating_indicator} "

                      tab_display_count         "9"
                      tab_truncate_start_format "#[fg=#f9e2af]  +{count}  "
                      tab_truncate_end_format   "#[fg=#f9e2af]   +{count} "

                      datetime        "#[fg=#6c7086,bold] {format} "
                      datetime_format "%d %b %H:%M"
                      datetime_timezone "Asia/Kolkata"
                  }
              }
          }
          tab name=""
      }

    '';
  };
}
